"""create health timeline table

Revision ID: 0c149ee4b845
Revises: bbdb6f54a243
Create Date: 2026-09-26 11:47:23.869872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c149ee4b845'
down_revision: Union[str, Sequence[str], None] = 'bbdb6f54a243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_timeline_id'), 'health_timeline', ['id'], unique=False)
    op.create_index(op.f('ix_health_timeline_user_id'), 'health_timeline', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_timeline_user_id'), table_name='health_timeline')
    op.drop_index(op.f('ix_health_timeline_id'), table_name='health_timeline')
    op.drop_table('health_timeline')
    # ### end Alembic commands ###
