"""create health profiles table

Revision ID: 194e833f1b2d
Revises: a98b713b94d4
Create Date: 2026-09-26 08:54:06.855800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '194e833f1b2d'
down_revision: Union[str, Sequence[str], None] = 'a98b713b94d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('allergies', sa.String(length=1000), nullable=True),
    sa.Column('medical_conditions', sa.String(length=2000), nullable=True),
    sa.Column('current_medications', sa.String(length=2000), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_profiles_id'), 'health_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_health_profiles_user_id'), 'health_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_profiles_user_id'), table_name='health_profiles')
    op.drop_index(op.f('ix_health_profiles_id'), table_name='health_profiles')
    op.drop_table('health_profiles')
    # ### end Alembic commands ###
