"""add doctor visits

Revision ID: 54918ddcf896
Revises: d08d97cf317a
Create Date: 2026-09-27 13:33:11.232237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54918ddcf896'
down_revision: Union[str, Sequence[str], None] = 'd08d97cf317a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('concern', sa.Text(), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('changes', sa.Text(), nullable=False),
    sa.Column('medications', sa.Text(), nullable=True),
    sa.Column('documents', sa.Text(), nullable=True),
    sa.Column('questions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_visits_id'), 'doctor_visits', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_visits_user_id'), 'doctor_visits', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_visits_user_id'), table_name='doctor_visits')
    op.drop_index(op.f('ix_doctor_visits_id'), table_name='doctor_visits')
    op.drop_table('doctor_visits')
    # ### end Alembic commands ###
