"""create health concerns table

Revision ID: 74d38e63f605
Revises: 194e833f1b2d
Create Date: 2026-09-26 10:59:23.987407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d38e63f605'
down_revision: Union[str, Sequence[str], None] = '194e833f1b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_concerns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('concern', sa.Text(), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_concerns_id'), 'health_concerns', ['id'], unique=False)
    op.create_index(op.f('ix_health_concerns_user_id'), 'health_concerns', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_concerns_user_id'), table_name='health_concerns')
    op.drop_index(op.f('ix_health_concerns_id'), table_name='health_concerns')
    op.drop_table('health_concerns')
    # ### end Alembic commands ###
