"""add health concern status

Revision ID: d08d97cf317a
Revises: 0c149ee4b845
Create Date: 2026-09-27 12:03:51.942429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd08d97cf317a'
down_revision: Union[str, Sequence[str], None] = '0c149ee4b845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_concerns', sa.Column('status', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_concerns', 'status')
    # ### end Alembic commands ###
